version: '3.7'

networks:
  public:
    driver: overlay
  private:
    driver: overlay
    attachable: true
volumes: 
  db-data:

services:
  mysql:
    image: mysql:8.0
    networks:
      - private
    volumes: 
      - db-data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: datawarehouse
      MYSQL_USER: datawarehouse
      MYSQL_PASSWORD: datawarehouse123
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - '3306:3306'
    deploy:
      replicas: 1
      update_config:
        order: 'stop-first'
      rollback_config:
        order: 'stop-first'
      resources:
        limits:
          cpus: '1.00'
          memory: 150M
        reservations:
          cpus: '0.25'
          memory: 150M
  data-warehouse:
    image: warehouse
    build:
      context: /
      dockerfile: Dockerfile

    networks:
      - public
      - private
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/datawarehouse?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: datawarehouse
      SPRING_DATASOURCE_PASSWORD: datawarehouse123
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
        max_attempts: 10
        delay: 5s
      update_config:
        parallelism: 1
        delay: 5s
      resources: 
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 200M
