version: '3.7'

networks:
  public:
    driver: overlay
  private:
    driver: overlay
    attachable: true
volumes: 
  db-data:

services:
  mysql:
    image: mysql:8.0
    networks:
      - private
      - public
    volumes: 
      - db-data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: datawarehouse
      MYSQL_USER: root
      MYSQL_PASSWORD: datawarehouse123
      MYSQL_ROOT_PASSWORD: datawarehouse123 
    ports:
      - '3306:3306'
  data-warehouse:
    image: data-warehouse
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - public
      - private
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/datawarehouse?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: datawarehouse123
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
        max_attempts: 15
        delay: 5s
      update_config:
        parallelism: 1
        delay: 5s

