version: '3.7'

networks:
  public:
    driver: overlay
  private:
    driver: overlay
    attachable: true
volumes: 
  db-data:

services:
  mysql:
    image: mysql:8.0
    networks:
      - private
      - public
    volumes: 
      - db-data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: datawarehouse
      MYSQL_USER: datawarehouse
      MYSQL_PASSWORD: datawarehouse123
      MYSQL_ROOT_PASSWORD: datawarehouse123 
    ports:
      - '3306:3306'
  data-warehouse:
    image: data-warehouse
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - public
      - private
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/datawarehouse?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: datawarehouse
      SPRING_DATASOURCE_PASSWORD: datawarehouse123

